#!/bin/bash
# Part of lab-in-a-box, it will install Insecure_app
# Author/s: Raul Mahiques
# License: GPLv3
#
#  This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program. If not, see <https://www.gnu.org/licenses/gpl-3.0.html>.


_VERSION="__LABVERSION__"
[[ "${1}" == "--version" || "${1}" == "-v" ]] && echo "${0##*/} ${_VERSION}" && exit 0

# load lab_creation defaults
if [[ -f /etc/lab_creation.defaults ]]
then
        . /etc/lab_creation.defaults
elif [[ -f lab_creation.defaults ]]
then
        . lab_creation.defaults
else
        echo "ERROR: Configuration file lab_creation.defaults not found in local path or /etc"
        exit 1
fi

# Load primary functions
. ${_primary_funtions} || exit 1

# load Kubernetes functions
. ${_lib_path}/k8s_functions.bash



# Load insecure-app related variables.
function load_insecure_app_vars() {
       _section="insecure_app"
       _load_vars
}



# Setup insecure-app
function setup_insecure_app() {
             
# For fleet
#                $ssh_command "kubectl apply -f https://raw.githubusercontent.com/SUSE-Technical-Marketing/insecure-app/main/fleet_cattle.yml"
#		$ssh_command "kubectl delete namespace ${insecure_app_ns}"
                $ssh_command "kubectl delete -n ${insecure_app_ns:-insecure-apps} deployment.app/${insecure_app_name:-webphotobook}"
		template_file=${_templ_addons_loc}/insecure_app/install.yml.tmpl
                process_templates | $ssh_command "kubectl apply -f -"
                template_file=${_templ_addons_loc}/insecure_app/service.yml.tmpl
                process_templates | $ssh_command "kubectl apply -f -"
                template_file=${_templ_addons_loc}/insecure_app/ingress.yml.tmpl
                process_templates | $ssh_command "kubectl apply -f -"
		if [[ "${insecure_app_DB_TYPE:-sqlite3}" == "mysql" ]]
		then
                        template_file=${_templ_addons_loc}/insecure_app/myconf.yml.tmpl
                        process_templates | $ssh_command "cat - > /tmp/myconf_temp.yml" 
 			# need some time until the pod is up
			sleep 100
			_pod_name=`$ssh_command "kubectl get pods -n ${insecure_app_ns:-insecure-apps} | grep -o '${insecure_app_name:-webphotobook}-[a-z0-9]*-[a-Z0-9]*'"`
                        echo "pod name: $_pod_name"
                         process_templates | $ssh_command "kubectl cp /tmp/myconf_temp.yml ${insecure_app_ns:-insecure-apps}/$_pod_name:myconf_temp.yml"
                        $ssh_command "kubectl exec -n ${insecure_app_ns:-insecure-apps}  -i ${_pod_name} -- ping -c 1 ${mariadb_name:-mariadb}"
			echo "## Prepare database"
                        $ssh_command "kubectl exec -n ${insecure_app_ns:-insecure-apps}  -i ${_pod_name} -- env CONFIG_FILE=myconf_temp.yml /usr/bin/python3 init_db.py"
                        $ssh_command "kubectl exec -n ${insecure_app_ns:-insecure-apps}  -i ${_pod_name} -- cp myconf_temp.yml myconf.yml"
			for _param in "APP_NAME=${insecure_app_long_name:-My Buggy App}" "BASIC_AUTH_PASSWORD=${insecure_app_admin_pwd:-admin123}" "DBNAME=${insecure_app_DBNAME:-photos}" "DB_FILE=${insecure_app_DB_FILE:-database.db}" "DB_TABLE_NAME=${insecure_app_DB_TABLE_NAME:-photos}" "DB_TYPE=${insecure_app_DB_TYPE:-sqlite3}" "DB_HOST=${insecure_app_DB_HOST:-mysql}" "DB_USER=${insecure_app_DB_USER:-root}" "DB_PWD=${insecure_app_DB_PWD:-password_change_me}" "IMAGES_LOCATION=${insecure_app_IMAGES_LOCATION:-images/}" "PORT=${insecure_app_port:-5000}" "SECRET_KEY=${insecure_app_SECRET_KEY:-abcde1234}"
			do
                                echo "     Setting ${_param//=*}"
				$ssh_command "curl http://${insecure_app_name:-webphotobook}.${clu_name}.${mydomain}/api/settings -d '${_param}' -s  >/dev/null || echo failed "
			done
        #                $ssh_command "kubectl exec -n ${insecure_app_ns:-insecure-apps}  -i ${_pod_name} -- /usr/bin/python3 init_db.py"
		fi
                echo "Insecure app should be available in a few minutes"
}



# load cluster vars
load_kclu_vars

# load rancher variables
load_rancher_vars

# load neuvector variables
load_nv_vars

# load insecure_app variables
load_insecure_app_vars



# find a server node or API url
for _vm_name in $(jq -r '.nodes | to_entries[].key' < ${inputFile} |xargs)
do
	load_vm_vars
	ssh_command="ssh  -o StrictHostKeyChecking=accept-new -q  root@${_vm_name}"
	echo "# Using node: $_vm_name"
	setup_insecure_app
        _dns_entry="${insecure_app_name:-webphotobook}.${clu_name}"
        add_service_dns
        echo "Service will be ready at ${insecure_app_name:-webphotobook}.${clu_name}.${mydomain}"
	sleep 60
	exit 1
	
done


