#!/bin/bash
# Part of lab-in-a-box, it will install wordpress
# Author/s: Raul Mahiques
# License: GPLv3
#
#  This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program. If not, see <https://www.gnu.org/licenses/gpl-3.0.html>.


_VERSION="__LABVERSION__"
[[ "${1}" == "--version" || "${1}" == "-v" ]] && echo "${0##*/} ${_VERSION}" && exit 0

# load lab_creation defaults
if [[ -f /etc/lab_creation.defaults ]]
then
        . /etc/lab_creation.defaults
elif [[ -f lab_creation.defaults ]]
then
        . lab_creation.defaults
else
        echo "ERROR: Configuration file lab_creation.defaults not found in local path or /etc"
        exit 1
fi

# Load primary functions
. ${_primary_funtions} || exit 1

# load Kubernetes functions
. ${_lib_path}/k8s_functions.bash

# Load insecure-app related variables.
function load_wordpress_vars() {
       _section="wordpress"
       _load_vars
}



# Setup insecure-app
function setup_wordpress() {
             
                $ssh_command "kubectl delete -n ${wordpress_ns:-wordpress} Service/${wordpress_name:-wordpress} PersistentVolumeClaim/mysql-pv-claim Deployment.app/${wordpress_name:-wordpress} Service/${wordpress_name:-wordpress}-mysql PersistentVolumeClaim/wp-pv-claim  Deployment.app/${wordpress_name:-wordpress}-mysql"

                for _template in kustomization.yaml  mysql_install.yml  wordpress_deployment.yaml
                do
                  template_file=${_templ_addons_loc}/wordpress/${_template}.tmpl
                  process_templates | $ssh_command "kubectl apply -f -"
		done
                echo "wordpress should be available in a few minutes in: ${wordpress_shorthn:-wordpress}.${clu_name}.${mydomain}"
}



# load cluster vars
load_kclu_vars

# load rancher variables
load_rancher_vars

# load wordpress variables
load_wordpress_vars



# find a server node or API url
for _vm_name in $(jq -r '.nodes | to_entries[].key' < ${inputFile} |xargs)
do
	load_vm_vars
	ssh_command="ssh  -o StrictHostKeyChecking=accept-new -q  root@${_vm_name}"
	echo "# Using node: $_vm_name"
	setup_wordpress
        _dns_entry="${wordpress_name:-wordpress}.${clu_name}"
        add_service_dns
        echo "Service will be ready at ${wordpress_name:-worpress}.${clu_name}.${mydomain}"
	sleep 60	
done


