#!/bin/bash
# Part of lab-in-a-box, it will install nv-demo-helm
# Author/s: Raul Mahiques
# License: GPLv3
#
#  This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program. If not, see <https://www.gnu.org/licenses/gpl-3.0.html>.

_VERSION="__LABVERSION__"
[[ "${1}" == "--version" || "${1}" == "-v" ]] && echo "${0##*/} ${_VERSION}" && exit 0

# load lab_creation defaults
if [[ -f /etc/lab_creation.defaults ]]
then
        . /etc/lab_creation.defaults
elif [[ -f lab_creation.defaults ]]
then
        . lab_creation.defaults
else
        echo "ERROR: Configuration file lab_creation.defaults not found in local path or /etc"
        exit 1
fi

# Load primary functions
. ${_primary_funtions} || exit 1

# load Kubernetes functions
. ${_lib_path}/k8s_functions.bash


# Load insecure-app related variables.
function load_nv-demo-helm_vars() {
       _section="nv-demo-helm"
       _load_vars
}



# Setup insecure-app
function setup_nv-demo-helm() {
             
#                $ssh_command "kubectl apply -f https://raw.githubusercontent.com/SUSE-Technical-Marketing/insecure-app/main/fleet_cattle.yml"
#		$ssh_command "kubectl delete namespace ${nv-demo-helm_ns}"
                $ssh_command "git clone https://github.com/horantj/nv-demo-helm.git /var/tmp/nv-demo-helm"
                $ssh_command "helm install -n ${nv_demo_helm_ns:-demo} --create-namespace --set exploit.image_tag=${nv_demo_helm_tag:-0.4} --set struts.ingress.enabled=true --set struts.ingress.host=struts-${nv_demo_helm_name:-nvdemohelm}.${clu_name}.${mydomain} demo-release /var/tmp/nv-demo-helm/nv-demo"
                echo "NV demo helm should be available in a few minutes, for instructions please visit: https://github.com/horantj/nv-demo-helm/tree/main"
}


# load cluster vars
load_kclu_vars

# load rancher variables
load_rancher_vars

# load neuvector variables
load_nv_vars

# load neuvector variables
load_nv-demo-helm_vars



# find a server node or API url
for _vm_name in $(jq -r '.nodes | to_entries[].key' < ${inputFile} |xargs)
do
	load_vm_vars
	ssh_command="ssh  -o StrictHostKeyChecking=accept-new -q  root@${_vm_name}"
	echo "# Using node: $_vm_name"
	setup_nv-demo-helm
#        _dns_entry="${nv-demo-helm_name:-webphotobook}.${clu_name}"
#        add_service_dns
#        echo "Service will be ready at ${nv-demo-helm_name:-webphotobook}.${clu_name}.${mydomain}"
	sleep 60
	exit 1
	
done


