#!/bin/bash
# Part of lab-in-a-box, it will install jenkins
# Author/s: Raul Mahiques
# License: GPLv3
#
#  This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program. If not, see <https://www.gnu.org/licenses/gpl-3.0.html>.

_VERSION="__LABVERSION__"
[[ "${1}" == "--version" || "${1}" == "-v" ]] && echo "${0##*/} ${_VERSION}" && exit 0

# load lab_creation defaults
if [[ -f /etc/lab_creation.defaults ]]
then
        . /etc/lab_creation.defaults
elif [[ -f lab_creation.defaults ]]
then
        . lab_creation.defaults
else
        echo "ERROR: Configuration file lab_creation.defaults not found in local path or /etc"
        exit 1
fi

# Load primary functions
. ${_primary_funtions} || exit 1

# load Kubernetes functions
. ${_lib_path}/k8s_functions.bash


# Setup Jenkins
#https://www.jenkins.io/doc/book/installing/kubernetes/
function setup_jenkins() {
                $ssh_command "kubectl create namespace jenkins"
                # create the volume
#                $ssh_command "kubectl apply -f ${jenkins_volume:-https://raw.githubusercontent.com/jenkins-infra/jenkins.io/master/content/doc/tutorials/kubernetes/installing-jenkins-on-kubernetes/jenkins-volume.yaml}"
                # create a service account
#                $ssh_command "kubectl apply -f ${jenkins_url:-https://raw.githubusercontent.com/jenkins-infra/jenkins.io/master/content/doc/tutorials/kubernetes/installing-jenkins-on-kubernetes/jenkins-sa.yaml}"
#                $ssh_command "curl -k https://raw.githubusercontent.com/jenkinsci/helm-charts/main/charts/jenkins/values.yaml | sed 's/^storageClass:/storageClass: jenkins-pv/' | sed -z 's/serviceAccount:\n[ ]*#.*\n[ ]*create: true\n\n[ ]*#.*\n[ ]*#.*\n[ ]*name:/serviceAccount:\n  create: false\n  name: jenkins/' >/tmp/jenkins-values.yaml"
 #               $ssh_command "helm upgrade -i jenkins jenkins/jenkins -n jenkins -f /tmp/jenkins-values.yaml"
                $ssh_command "helm upgrade -i jenkins jenkins/jenkins -n jenkins"
                $ssh_command 'export jsonpath="{.data.jenkins-admin-password}"; export secret=$(kubectl get secret -n jenkins jenkins -o jsonpath=$jsonpath); echo "ADMIN PASSWORD: $(echo $secret | base64 --decode)"'
                $ssh_command "kubectl create -n jenkins ingress jenkins --rule=jenkins.${clu_name}.${mydomain}/=jenkins-server:443"
}


# Setup Jenkins helm respoitory
function setup_jenkins_repo() {
        _repo_name="${jenkins_rel:-jenkins}"
        _repo_url="${jenkins_repo_url:-https://charts.jenkins.io}"
        helm_repo_add
}


# load cluster vars
load_kclu_vars

# load rancher variables
load_rancher_vars

# load neuvector variables
load_jenkins_vars


# find a server node or API url
for _vm_name in $(jq -r '.nodes | to_entries[].key' < ${inputFile} |xargs)
do
	load_vm_vars
	ssh_command="ssh  -o StrictHostKeyChecking=accept-new -q  root@${_vm_name}"
	if [[ "${INSTALL_RKE2_TYPE}" == "server" || "${INSTALL_RKE2_TYPE}" == "" ]]
	then
		echo "# Using node: $_vm_name"
		setup_jenkins_repo
		setup_jenkins
		sleep 60
		exit 1
	fi
done


