#!/bin/bash
# Part of lab-in-a-box, it will install strus demo apps
# Author/s: Raul Mahiques
# License: GPLv3
#
#  This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program. If not, see <https://www.gnu.org/licenses/gpl-3.0.html>.


_VERSION="__LABVERSION__"
[[ "${1}" == "--version" || "${1}" == "-v" ]] && echo "${0##*/} ${_VERSION}" && exit 0

# load lab_creation defaults
if [[ -f /etc/lab_creation.defaults ]]
then
        . /etc/lab_creation.defaults
elif [[ -f lab_creation.defaults ]]
then
        . lab_creation.defaults
else
        echo "ERROR: Configuration file lab_creation.defaults not found in local path or /etc"
        exit 1
fi

# Load primary functions
. ${_primary_funtions} || exit 1

# load Kubernetes functions
. ${_lib_path}/k8s_functions.bash

# Load struts demo related variables.
function load_struts_demo_vars() {
       _section="struts_demo"
       _load_vars
}



# Setup NV testing
function setup_struts_demo() {

                $ssh_command "kubectl delete -n ${struts_demo_ns:-struts} service/${struts_demo_name:-struts} deployment.apps/${struts_demo_name:-struts} deployment.apps/attacker ingress/${struts_demo_name:-struts}"
                for _template_to_run in namespace.yml.tmpl install.yml.tmpl service.yml.tmpl ingress.yml.tmpl
 		do
			template_file=${_templ_addons_loc}/struts_demo/${_template_to_run}
	                process_templates | $ssh_command "kubectl apply -f -"
		done
                if [[ "$struts_demo_attacker" == "1" ]]
		then
			template_file=${_templ_addons_loc}/struts_demo/attacker_install.yml.tmpl
                        process_templates | $ssh_command "kubectl apply -f -"
			sleep 60
                        _pod_name=`$ssh_command "kubectl get pods -n ${struts_demo_ns:-struts} | grep -o '${struts_demo_name:-struts}-[a-z0-9]*-[a-Z0-9]*'"`
                        $ssh_command "kubectl exec -n ${struts_demo_ns:-struts}  -i ${_pod_name} -- apk add --update --no-cache python3"


			template_file=${_templ_addons_loc}/struts_demo/attacker_install.yml.tmpl
                        process_templates | $ssh_command "kubectl apply -f -"
		fi
                echo "Struts demo app ( https://github.com/skywalke34/struts-demo ) should be available in a few seconds"
}



# load cluster vars
load_kclu_vars

# load rancher variables
load_rancher_vars

# load neuvector variables
load_nv_vars

# load Struts demo app variables
load_struts_demo_vars



# find a server node or API url
for _vm_name in $(jq -r '.nodes | to_entries[].key' < ${inputFile} |xargs)
do
	load_vm_vars
	ssh_command="ssh  -o StrictHostKeyChecking=accept-new -q  root@${_vm_name}"
	echo "# Using node: $_vm_name"
	setup_struts_demo
        _dns_entry="${struts_demo_name:-struts}.${clu_name}"
        add_service_dns
        echo "Service will be ready at http://${struts_demo_name:-struts}.${clu_name}.${mydomain}/super-app"
	sleep 60
	exit 1
	
done


