#!/bin/bash
# Part of lab-in-a-box, it will install LongHorn
# Author/s: Raul Mahiques
# License: GPLv3
#
#  This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program. If not, see <https://www.gnu.org/licenses/gpl-3.0.html>.


_VERSION="__LABVERSION__"
[[ "${1}" == "--version" || "${1}" == "-v" ]] && echo "${0##*/} ${_VERSION}" && exit 0

# load lab_creation defaults
if [[ -f /etc/lab_creation.defaults ]]
then
        . /etc/lab_creation.defaults
elif [[ -f lab_creation.defaults ]]
then
        . lab_creation.defaults
else
        echo "ERROR: Configuration file lab_creation.defaults not found in local path or /etc"
        exit 1
fi

# Load primary functions
. ${_primary_funtions} || exit 1

# load Kubernetes functions
. ${_lib_path}/k8s_functions.bash

# Setup SUSE Longhorn helm repository
function setup_lh_repo() {
        _repo_name="${lh_rel:-longhorn}"
        _repo_url="${lh_repo_url:-https://charts.longhorn.io}"
        helm_repo_add
}


 # Setup SUSE Longhorn
function setup_lh() {
                $ssh_command "zypper install -y open-iscsi cryptsetup; systemctl enable --now iscsid.service ; modprobe iscsi_tcp"
                $ssh_command "kubectl create namespace longhorn-system"
                $ssh_command "helm upgrade -i longhorn longhorn/longhorn --namespace longhorn-system --set ingress.enabled=true --set ingress.host=${lh_shorthn:-longhorn}.${clu_name}.${mydomain}  --set persistence.migratable=true --set longhornUI.replicas=1"
                echo "Longhorn should be available in a few minutes in: ${lh_shorthn:-longhorn}.${clu_name}.${mydomain}"
}
 

# load cluster vars
load_kclu_vars

# load rancher variables
load_rancher_vars

# load longhorn variables
load_lh_vars




# find a server node or API url
for _vm_name in $(jq -r '.nodes | to_entries[].key' < ${inputFile} |xargs)
do
	load_vm_vars
	ssh_command="ssh  -o StrictHostKeyChecking=accept-new -q  root@${_vm_name}"
	if [[ "${INSTALL_RKE2_TYPE}" == "server" || "${INSTALL_RKE2_TYPE}" == "" ]]
	then
		echo "# Using node: $_vm_name"
		setup_helm
		setup_lh_repo
		setup_lh
		sleep 60
		exit 1
	fi
done


