#!/bin/bash
# Part of lab-in-a-box, it will install Rancher
# Author/s: Raul Mahiques
# License: GPLv3
#
#  This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program. If not, see <https://www.gnu.org/licenses/gpl-3.0.html>.

_VERSION="__LABVERSION__"
[[ "${1}" == "--version" || "${1}" == "-v" ]] && echo "${0##*/} ${_VERSION}" && exit 0

# load lab_creation defaults
if [[ -f /etc/lab_creation.defaults ]]
then
        . /etc/lab_creation.defaults
elif [[ -f lab_creation.defaults ]]
then
        . lab_creation.defaults
else
        echo "ERROR: Configuration file lab_creation.defaults not found in local path or /etc"
        exit 1
fi

# Load primary functions
. ${_primary_funtions} || exit 1

# load Kubernetes functions
. ${_lib_path}/k8s_functions.bash || exit 1

# Setup SUSE Rancher helm respoitory
function setup_rancher_repo() {
        _repo_name="${rancher_rel:-rancher-stable/rancher}"
        _repo_url="${rancher_repo_url:-https://releases.rancher.com/server-charts/stable}"
        helm_repo_add

        _repo_name="${rancher_cert_repo_name:-jetstack}"
        _repo_url="${rancher_cert_repo_url:-https://charts.jetstack.io}"
        helm_repo_add
} 


# Setup cert-manager
function setup_cert-manager() {
        # https://cert-manager.io/docs/installation/helm/
        _msg="# Setup Cert-manager" show_nicer_messages

        local _install_cert_manager="helm upgrade -i cert-manager jetstack/cert-manager ${cert_manager_ver} --namespace cert-manager --create-namespace --set installCRDs=true"
        $ssh_command "${_install_cert_manager}" || _msg="$ssh_command \"${_install_cert_manager}\"" fail_with_error
        $ssh_command "kubectl wait pods -n cert-manager -l app.kubernetes.io/instance=cert-manager --for condition=Ready --timeout=120s 2>/dev/null"
        $ssh_command "kubectl apply -f -" <<EOF
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-ci
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: none@someunknowndomain.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - http01:
          ingress:
            class: ${ingressClassname:-traefik}
...
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: none@someunknowndomain.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: ${ingressClassname:-traefik}
EOF



}

 
# Setup SUSE Rancher
function setup_rancher() {
        msg="# Setup Rancher ${rancher_helm_rel:-rancher} in cluster \"${clu_name}\"" show_nicer_messages
#        $ssh_command "helm upgrade -i ${rancher_helm_rel:-rancher} ${rancher_helm_chart} --create-namespace --namespace cattle-system --set hostname=\"${rancher_shorthn}.${clu_name}.${mydomain}\" ${rancher_version} --set bootstrapPassword=\"${rancher_initial_pwd}\" --set replicas=${rancher_replicas:-2} --set ingress.extraAnnotations.'cert-manager\.io/cluster-issuer'=letsencrypt-prod --set ingress.tls.source=secret --set ingress.tls.secretName=tls-rancher --set agentTLSMode=\"system-store\"" || exit 1

        $ssh_command "helm upgrade -i ${rancher_helm_rel:-rancher} ${rancher_helm_chart} --create-namespace --namespace cattle-system --set hostname=\"${rancher_shorthn}.${clu_name}.${mydomain}\" ${rancher_version} --set bootstrapPassword=\"${rancher_initial_pwd}\" --set replicas=${rancher_replicas:-2} " || exit 1

        # verify it's up and running
        # kubectl -n cattle-system rollout status deploy/rancher
        # kubectl -n cattle-system get deploy rancher

        _msg="## Add Rancher DNS" show_nicer_messages
        _dns_entry="${rancher_shorthn:-ERROR_ranchershort}.${clu_name}"
        add_service_dns



        local clu_type_u="${clu_type^^}" 
        local matching_nodes
        matching_nodes=$(jq -r --arg ctype "INSTALL_${clu_type_u}_TYPE" --arg cname "${clu_name}" '
            .nodes | to_entries[] | select(.value[$ctype] == "server" and .value.kcluster == $cname) | .key
        ' < "${inputFile}")

        for _dns in $matching_nodes; do
            add_dns_to_named_rr
        done

        systemctl restart named

        _msg="Wait for rancher to be ready" show_nicer_messages
        $ssh_command 'kubectl wait pods -n cattle-system -l app=rancher --for condition=Ready --timeout=300s'
#        $ssh_command 'while ! kubectl get secret rancher-tls --namespace cattle-system 2>/dev/null; do sleep 1; done; sleep 10'
        sleep 60

        initial_rancher_pwd=$($ssh_command "kubectl get secret --namespace cattle-system bootstrap-secret -o jsonpath='{.data.bootstrapPassword}' | base64 -d") || { _msg="Failed to retrieve bootstrap secret" fail_with_error; }

        _msg="# Initial password: ${initial_rancher_pwd}" show_nicer_messages
#        initial_rancher_pwd=`$ssh_command "kubectl get secret --namespace cattle-system bootstrap-secret -o go-template='{{.data.bootstrapPassword|base64decode}}{{ \"\n\" }}'" || exit 1`

}



# load cluster vars
load_kclu_vars

# load rancher variables
load_rancher_vars


# find a server node or API url
load_vm_vars

ssh_command="ssh  -o StrictHostKeyChecking=accept-new -q  root@${_vm_name}"

if [[ "${INSTALL_RKE2_TYPE}" == "server" || "${INSTALL_RKE2_TYPE}" == "" ]]
then
	_msg="Using node: \e[1;91m\"${_vm_name}\"\e[0m" show_nicer_messages
	setup_helm
	_msg="Setup_rancher_repo" show_nicer_messages
	setup_rancher_repo
	setup_cert-manager
	setup_rancher
	exit 1
fi

